Options:
 #The number of rows for a bookshelf (Allows 1-6)
  BookShelfRows: 2

  #Whether to use the item whitelist or not
  UseWhitelist: true

  #Items which is allowed to be placed into a bookshelf
  #See this for item names: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
  Whitelist:
   - BOOK
   - WRITABLE_BOOK
   - WRITTEN_BOOK
   - ENCHANTED_BOOK
   - KNOWLEDGE_BOOK

  #The default inventory name for an unnamed bookshelf
  Title: "Bookshelf"

  NoPermissionToReloadMessage: "&cYou do not have permission use this command!"
  NoPermissionToUpdateMessage: "&cYou do not have permission use this command!"

  #Play particles or not when open
  ParticlesWhenOpened: true

  #Whether to allow bookshelves to work with hoppers
  #Performace heavy, not recommended
  EnableHopperSupport: false

  #Whether to allow bookshelves to work with droppers
  EnableDropperSupport: false

  #Whether to enable enchantment table boosting
  EnableEnchantmentTableBoosting: true
  #Max percentage of the enchantment table boosting feature
  #Accepts integer from 0 - 100
  EnchantmentTableBoostingMaxPercentage: 80

  #Enable update notifications for admins
  Updater: true